spring:
  application:
    name: qz

  datasource:
    url: jdbc:mysql://localhost:3306/new_irm?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: kkk
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10000
      minimum-idle: 10
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 3000
      pool-name: HikariIrm

  #  quartz 集群配置
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 100
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
      #初始化表结构
      #jdbc:
    #initialize-schema: never


mybatis:
  type-aliases-package: com.jd.irm.domain
  mapper-locations:  classpath:mapper/**.xml
  configuration:
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    #    配置批量插入
    default-executor-type: simple
    default-statement-timeout: 3000
server:
  port: 8083